apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: adsz/capstone:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
---
apiVersion: v1
kind: Service
metadata:
  name: capstone
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  selector:
    app: capstone
  type: LoadBalancer