version: '2.1'
orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3
jobs:
    lint:
        docker:
            # Use the same Docker base as the project 
            - image: python:3.10-slim-bullseye

        working_directory: ~/.capstone

        steps:
            - checkout
            - run:
                name: install dependencies
                command: |
                    apt update
                    apt install -y make wget curl pylint docker
                    wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
                    chmod +x /bin/hadolint
                    make install
            - run:
                name: run lint
                command: |
                    make lint 


    build-docker-image:
        docker:
            # Use the same Docker base as the project 
            - image: cimg/base:current
        
        working_directory: ~/capstone

        steps:
            - checkout
            
            - setup_remote_docker:
                version: 20.10.14
                docker_layer_caching: true

            - run:
                name: Build docker image
                command: |
                    docker build --tag=capstone . --no-cache
                    docker image ls

    upload-docker:
        docker:
          - image: cimg/base:current
    
        working_directory: ~/capstone
    
        steps:
          - checkout
    
          - run:
              name: Upload Docker to Dockerhub
              command: |
                docker image ls 
                echo "Docker ID and Image: capstone"
                docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
                docker tag "capstone" $DOCKERHUB_USERNAME/"capstone":stable
                docker push $DOCKERHUB_USERNAME/"capstone":stable  
# jobs:
#   test-cluster:
#     docker:
#       - image: 'cimg/python:3.10'
#     parameters:
#       cluster-name:
#         description: |
#           Capstone cluster
#         type: string
#     steps:
#       - kubernetes/install:
#           kubectl-version: v1.22.0
#       - aws-eks/update-kubeconfig-with-authenticator:
#           cluster-name: capstone-cluster
#       - run:
#           command: |
#             kubectl get services
#           name: Test cluster
workflows:
    hadolint:
      jobs:
        - lint
        - build-docker-image
        - upload-docker
#   deployment:
#     jobs:
#       - aws-eks/create-cluster:
#           cluster-name: capstone-cluster
#       - test-cluster:
#           cluster-name: capstone-cluster
#           requires:
#             - aws-eks/create-cluster
#       - aws-eks/delete-cluster:
#           cluster-name: capstone-cluster
#           requires:
#             - test-cluster
